[package]
name = "TokenUtilityPrice"
version = "0.0.1"
published-at = "0x4dcb1a74837e2cb655c89155451242985020d9916b0a8374f0e1476500f7f105"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.26.2" }
flowxswap = { git = "https://github.com/TokenUtility/flowx-interface.git", subdir = "", rev = "mainnet" }

[addresses]
TokenUtilityPrice = "0x4dcb1a74837e2cb655c89155451242985020d9916b0a8374f0e1476500f7f105"
sui = "0x2"